### ISSUE TITLE
issue installing Ruby requirements

### ISSUE THREAD

**Issue by siobhanmacardle** [gchure/reproducible_website#3]
I was able to install Ruby and install Jekyll as instructed by the Installation page of the reproducible_website wiki. I cloned the reproducible_website repository to my local computer (macOS).  From the cloned repository, I tried to issue the "bundle install" command in the terminal and I got this error:

![Screen Shot 2020-06-27 at 11 06 54 AM](https://user-images.githubusercontent.com/58827368/85929113-1152c200-b867-11ea-8fa5-7795bdb30ca7.png)
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this
to your Gemfile:
source 'https://rubygems.org'
Could not find concurrent-ruby-1.1.5 in any of the sources

I also got the following dependebot alerts:

![Screen Shot 2020-06-26 at 8 55 24 PM](https://user-images.githubusercontent.com/58827368/85929097-ed8f7c00-b866-11ea-946f-10f0faef46fe.png)
![Screen Shot 2020-06-26 at 8 55 08 PM](https://user-images.githubusercontent.com/58827368/85929098-eec0a900-b866-11ea-8eef-557f30355ae5.png)

**Comment by gchure** [comment]
These comments have been addressed. Thanks for bringing it to my attention. I'm going to close the issue, but feel free to reopen if you are still having problems.
